name: ginga # you probably want to 'snapcraft register <name>'
version: '0.1+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: The iTV middleware # 79 char long summary
description: |
  This is snap for Ginga.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  ginga:
    command: usr/bin/ginga
    plugs: [home, network, x11]

parts:
  ginga:
    # See 'snapcraft plugins'
    source: https://github.com/telemidia/ginga.git
    source-type: git
    plugin: autotools
    build-packages:
      - build-essential
      - pkg-config
      - libtool
      - liblua5.2-dev
      - libcairo2-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgtk-3-dev
      - libxerces-c-dev


